### ISSUE TITLE
Diminuir fonte de integrations em card de grupo

### ISSUE THREAD

**Issue by pserey** [GIMS-P1-2024-1/frontend#1]
![image](https://github.com/user-attachments/assets/b705279d-ee0b-48cf-8e2d-20a6079b82e0)

**Comment by wendell-rafael** [comment]
diminiu, aumentei o espaço e deixei mais parecido como ta no figma
![image](https://github.com/user-attachments/assets/b7b70e58-280f-433d-bafa-138288961dd0)
