### ISSUE TITLE
Mudar nome da aba e favicon

### ISSUE THREAD

**Issue by pserey** [GIMS-P1-2024-1/frontend#4]
Pode deixar favicon do React enquanto não temos logo, mas mudar o nome pra GIMS

![image](https://github.com/user-attachments/assets/cf3d65f9-1d71-4d80-99d4-09f8b5a233af)

**Comment by wendell-rafael** [comment]
![image](https://github.com/user-attachments/assets/069e7cd5-4e6e-440c-9f94-21ac4a4ab436)
